# Site settings
title: Knight Hacks
email: team@knighthacks.org
description: > # this means to ignore newlines until "baseurl:"
  Knight Hacks is a student organization at the University of Central Florida, devoted to the builder in everyone. As an RSO, we provide workshops, activities, and support for the hackers of UCF, giving the tools and skills needed to build something extraordinary.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://club.knighthacks.org" # the base hostname & protocol for your site
twitter_username: knighthacks
github_username:  knighthacks

# Build settings
markdown: kramdown
