---
  title: Knight Hacks
  url: ''
  author: The Knight Hacks Team
  email: team@knighthacks.org
  description: Giving people a space to learn and do things they’ve never done before
  socialLinks:
    facebook: 'https://www.facebook.com/groups/knighthacksclub/'
    twitter: 'https://twitter.com/knighthacks'
    github: 'https://github.com/knighthacks'
    instagram: 'https://instagram.com/knighthacks/'
  eventDisplayLimit: 4
  workshopDisplayLimit: 4
  events:
    -
      name: 'No meeting'
      date: 11/27/15
    -
      name: 'Rails Workshop (Last Meeting)'
      date: 12/4/15
    -
      name: 'Knight Hacks Hackathon'
      date: 01/15/16
      url: 'http://knighthacks.org/'
  workshops:
    -
      name: 'Front End Web Development'
      date: 11/13/2015
      time: 6:15 PM
      url: '/workshops/frontend-web-development'
    -
      name: 'Introduction to Web Development'
      date: 10/30/2015
      time: 6:15 PM
      url: '/workshops/intro-web-development'
    -
      name: 'Introduction to Android'
      date: 10/23/2015
      time: 6:15 PM
      url: '/workshops/intro-android-workshop'
    -
      name: 'Introduction to Vim'
      date: 10/16/2015
      time: 6:15 PM
      url: '/workshops/vim-workshop'
    -
      name: 'Advanced Git Workshop'
      date: 10/9/2015
      time: 6:15 PM
      url: '/workshops/advanced-git-workshop'
    -
      name: 'Set up a free cloud server with Azure'
      date: 9/25/2015
      time: 6:15 PM
      url: '/workshops/azure'
    -
      name: '`git` Workshop'
      date: 9/18/2015
      time: 6:15 PM
      url: '/workshops/git-workshop'
    -
      name: 'Using GitHub effectively (Slides)'
      date: 9/17/2015
      time: 7:30 PM
      url: 'https://docs.google.com/presentation/d/1hbq1V4rirMkDv0saQVP-cqzi0SJr04xF-DW1FhbDrMk/edit?usp=sharing'
    -
      name: 'Command Line Workshop'
      date: 9/11/2015
      time: 6:15 PM
      url: '/workshops/command-line'
