---
  title: "Knight Hacks"
  url: "http://knighthacks.org"
  author: "The Knight Hacks Team"
  email: "contact@knighthacks.org"
  description: "Giving people a space to learn and do things they’ve never done before"
