---
  title: Knight Hacks
  url: ""
  author: The Knight Hacks Team
  email: team@knighthacks.org
  description: Giving people a space to learn and do things they’ve never done before
  socialLinks:
    facebook: "https://www.facebook.com/groups/knighthacksclub/"
    twitter: "https://twitter.com/knighthacks"
    github: "https://github.com/knighthacks"
    instagram: "https://instagram.com/knighthacks/"

